name: user_repository
description: A Dart package for managing user data and authentication.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter
  firebase_auth: 
  cupertino_icons: ^1.0.8
  firebase_storage: 
  cloud_firestore: 
  rxdart: ^0.28.0
  flutter_logs: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true