// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCNvdCZMkGUcqdy_-qVuW9Xl7unJOjiqc',
    appId: '1:1060909337999:web:4102d163262b67cc7a4ffa',
    messagingSenderId: '1060909337999',
    projectId: 'pizzaapp-b5908',
    authDomain: 'pizzaapp-b5908.firebaseapp.com',
    storageBucket: 'pizzaapp-b5908.firebasestorage.app',
    measurementId: 'G-999HJ8FCB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ_Ujj2pkClh35TH6-_ibLg49ftUjr6Ws',
    appId: '1:1060909337999:android:c251be6741538a177a4ffa',
    messagingSenderId: '1060909337999',
    projectId: 'pizzaapp-b5908',
    storageBucket: 'pizzaapp-b5908.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv3iKWi-nT2cwKIMNsWQEkyXragILDtdw',
    appId: '1:1060909337999:ios:926cc83f4fa1f16a7a4ffa',
    messagingSenderId: '1060909337999',
    projectId: 'pizzaapp-b5908',
    storageBucket: 'pizzaapp-b5908.firebasestorage.app',
    iosBundleId: 'com.example.pizzaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv3iKWi-nT2cwKIMNsWQEkyXragILDtdw',
    appId: '1:1060909337999:ios:926cc83f4fa1f16a7a4ffa',
    messagingSenderId: '1060909337999',
    projectId: 'pizzaapp-b5908',
    storageBucket: 'pizzaapp-b5908.firebasestorage.app',
    iosBundleId: 'com.example.pizzaapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCNvdCZMkGUcqdy_-qVuW9Xl7unJOjiqc',
    appId: '1:1060909337999:web:3e637cd98ffbda527a4ffa',
    messagingSenderId: '1060909337999',
    projectId: 'pizzaapp-b5908',
    authDomain: 'pizzaapp-b5908.firebaseapp.com',
    storageBucket: 'pizzaapp-b5908.firebasestorage.app',
    measurementId: 'G-3HM99K8113',
  );

}